image: docker:latest

services:
  - docker:dind

variables:
  CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE/$CI_DEFAULT_BRANCH:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
  

stages:
  - build
  - test
  - race

include:
  - template: Jobs/Test.gitlab-ci.yml
 
build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE .
  after_script:
    - docker push $IMAGE

test:
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - cp -R . /tmp/app
    - /bin/herokuish buildpack test
  after_script:
    - echo "Our race track has been tested!"
  needs: []

super_fast_test:
  stage: test
  script:
    - echo "If your not first your last"
    - return 0
  needs: []

build_car_a:
 stage: build
 script:
  - echo "build_car_a"

build_car_b:
 stage: build
 script:
  - echo "build_car_b"

build_car_c:
 stage: build
 script:
  - echo "build_car_c"

build_car_d:
 stage: build
 script:
  - echo "build_car_d"

build_car_e:
 stage: build
 script:
  - echo "build_car_e"

build_car_f:
 stage: build
 script:
  - echo "build_car_f"

test_car_a:
 stage: test
 needs: [build_car_a]
 script:
  - echo "test_car_a"

test_car_b:
 stage: test
 needs: [build_car_b]
 script:
  - echo "test_car_b"

test_car_c:
 stage: test
 needs: [build_car_c]
 script:
  - echo "test_car_c"

test_car_d:
 stage: test
 needs: [build_car_d]
 script:
  - echo "test_car_d"

test_car_e:
 stage: test
 needs: [build_car_e]
 script:
  - echo "test_car_e"

test_car_f:
 stage: test
 needs: [build_car_f]
 script:
  - echo "test_car_f"

race_car_a:
 stage: race
 needs: [test_car_a]
 script:
  - echo "race_car_a"

race_car_b:
 stage: race
 needs: [test_car_b]
 script:
  - echo "race_car_b"

race_car_c:
 stage: race
 needs: [test_car_c]
 script:
  - echo "race_car_c"

race_car_d:
 stage: race
 needs: [test_car_d]
 script:
  - echo "race_car_d"

race_car_e:
 stage: race
 needs: [test_car_e]
 script:
  - echo "race_car_e"

race_car_f:
 stage: race
 needs: [test_car_f]
 script:
  - echo "race_car_f"

