
apiVersion: v1
kind: Namespace
metadata:
  name: tanuki-racing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanuki-racing
  namespace: tanuki-racing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanuki-racing
  namespace: tanuki-racing
spec:
  selector:
    matchLabels:
      app: tanuki-racing
  template:
    metadata:
      labels:
        app: tanuki-racing
    spec:
      containers:
      - image: registry.gitlab.com/gitlab-learn-labs/webinars/tanuki-racing/tanuki-racing-application/main:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
        name: tanuki-racing
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: gitlab-credentials
      securityContext: {}
      serviceAccountName: tanuki-racing
